import {useEffect,useMemo,useRef,useState} from 'react';
import {BarChart3,CalendarDays,Delete,Eraser,HelpCircle,Lightbulb,Share2,X} from 'lucide-react';
import {answerFor,displayWord,hintFor,isWord} from './corpus';
import {dayNumber,loadGames,localDate,newGame,normalize,saveGame,score,statistics,type Game,type Mark} from './game';

const ROWS=['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'];
type Modal='help'|'stats'|'archive'|'result'|'hint'|null;
export default function App(){
 const today=localDate(),params=new URLSearchParams(location.search),requested=params.get('data'),archive=params.get('modo')==='arquivo'&&!!requested;
 const date=archive?requested!:today,number=dayNumber(date),locked=number<1||date>today;
 const key=`${archive?'a':'d'}:${date}`,existing=loadGames()[key];
 const [game,setGame]=useState<Game>(existing||newGame(date,archive));const [modal,setModal]=useState<Modal>(locked?'archive':null);const [message,setMessage]=useState('');const [invalid,setInvalid]=useState(false);const [now,setNow]=useState(new Date());const answer=answerFor(number);
 const gameRef=useRef(game);gameRef.current=game;
 const commit=(next:Game)=>{next.updatedAt=new Date().toISOString();setGame(next);saveGame(next)};
 useEffect(()=>{const tick=()=>{setNow(new Date());if(localDate()!==today&&!gameRef.current.archive)location.reload()};const id=setInterval(tick,1000);addEventListener('focus',tick);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(id);removeEventListener('focus',tick);document.removeEventListener('visibilitychange',tick)}},[today]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(modal||game.status!=='playing')return;if(/^[a-zA-ZçÇáàãâéêíóôõúü]$/.test(e.key))input(e.key);else if(e.key==='Backspace'){e.preventDefault();backspace()}else if(e.key==='Enter'){e.preventDefault();submit()}else if(e.key===' '||e.key==='-'){e.preventDefault();input('_')}};addEventListener('keydown',down);return()=>removeEventListener('keydown',down)});
 const input=(letter:string)=>{if(game.status!=='playing'||game.draft.length>=5)return;setInvalid(false);commit({...game,draft:game.draft+normalize(letter)})};
 const backspace=()=>{setInvalid(false);commit({...game,draft:game.draft.slice(0,-1)})};
 const reject=(text:string)=>{setInvalid(false);requestAnimationFrame(()=>setInvalid(true));toast(text)};
 const submit=()=>{const word=normalize(game.draft);if(word.length!==5||word.includes('_'))return reject('Complete as cinco letras.');if(!isWord(word))return reject('Palavra não reconhecida.');setInvalid(false);const clue=score(word,answer.key),won=word===answer.key,attempts=[...game.attempts,{word,display:displayWord(word),clue,marks:Array(5).fill('neutral') as Mark[]}];const status=won?'won':attempts.length===8?'lost':'playing';commit({...game,draft:'',attempts,status});if(status!=='playing')setTimeout(()=>setModal('result'),800)};
 const toast=(s:string)=>{setMessage(s);setTimeout(()=>setMessage(''),2200)};
 const mark=(ri:number,ci:number)=>{const order:Mark[]=['neutral','absent','present','correct'];const attempts=game.attempts.map((a,i)=>i===ri?{...a,marks:a.marks.map((m,j)=>j===ci?order[(order.indexOf(m)+1)%4]:m)}:a);commit({...game,attempts})};
 const clearMarks=()=>commit({...game,attempts:game.attempts.map(a=>({...a,marks:Array(5).fill('neutral') as Mark[]}))});
 const hint=()=>{if(!game.attempts.length)return toast('A dica é liberada após uma tentativa.');setModal('hint')};
 const applyHint=()=>{const word=hintFor(answer.key,game.attempts,game.draft);if(!word)return toast('Nenhuma outra palavra compatível foi encontrada.');commit({...game,draft:word,hintUsed:true});toast('Uma palavra possível foi preenchida.')};
 const used=new Set(game.attempts.flatMap(a=>[...a.word]));
 const remaining=Math.max(0,new Date(now.getFullYear(),now.getMonth(),now.getDate()+1).getTime()-now.getTime()),hh=String(Math.floor(remaining/3600000)).padStart(2,'0'),mm=String(Math.floor(remaining%3600000/60000)).padStart(2,'0'),ss=String(Math.floor(remaining%60000/1000)).padStart(2,'0');
 return <main className="app"><header><button aria-label="Abrir arquivo" onClick={()=>setModal('archive')}><CalendarDays/></button><button className="brand" aria-label={game.status==='playing'?'Termo500':'Abrir resultado da partida'} onClick={()=>game.status!=='playing'&&setModal('result')}><span className="mini"><i>T</i><i>5</i><i>0</i></span><h1>TERMO<span>500</span></h1></button><nav><button aria-label="Como jogar" onClick={()=>setModal('help')}><HelpCircle/></button><button aria-label="Estatísticas" onClick={()=>setModal('stats')}><BarChart3/></button></nav></header>
 <section className="meta"><span>{archive?'ARQUIVO':'PALAVRA DO DIA'}</span><b>#{Math.max(1,number)}</b></section>
 <section className="board" aria-label="Tabuleiro de oito tentativas">
  {Array.from({length:8},(_,ri)=>{const a=game.attempts[ri],active=ri===game.attempts.length&&game.status==='playing';const chars=a?[...a.display]:active?[...game.draft.padEnd(5,' ')]:Array(5).fill(' ');return <div className={`board-row ${a?'submitted':''} ${active&&invalid?'invalid':''}`} key={ri}>{chars.map((c,ci)=><button disabled={!a} aria-label={a?`Marcar letra ${c}, tentativa ${ri+1}`:`Posição ${ci+1}`} className={`tile ${a?a.marks[ci]:active?'active':''}`} style={{animationDelay:`${ci*65}ms`}} onClick={()=>a&&mark(ri,ci)} key={ci}>{c==='_'?'_':c}</button>)}<div className="counts">{(['correct','present','absent'] as const).map((k,i)=><div key={k} className={`count ${k}`} style={{animationDelay:`${i*130+260}ms`}} aria-label={a?`${a.clue[k]} letras ${k==='correct'?'certas':k==='present'?'presentes':'ausentes'}`:undefined}>{a?a.clue[k]:''}</div>)}</div></div>})}
 </section>
 <div className="message" role="status">{message}</div>
 <section className="keyboard" aria-label="Teclado virtual">{ROWS.map((row,i)=><div className="keyrow" key={row}>{i===2&&<button className="action" aria-label="Limpar marcações" onClick={clearMarks}><Eraser/></button>}{[...row].map(k=><button className={used.has(k)?'used':''} onClick={()=>input(k)} key={k}>{k}</button>)}{i===2&&<button className="action" aria-label="Apagar letra" onClick={backspace}><Delete/></button>}</div>)}<div className="keyrow actions"><button onClick={hint} disabled={!game.attempts.length||game.status!=='playing'}><Lightbulb/><span>DICA</span></button><button onClick={()=>input('_')}>ESPAÇO</button><button onClick={submit} disabled={game.status!=='playing'}>ENTER</button></div></section>
 <footer>{archive?<button onClick={()=>location.href='./'}>Voltar ao jogo de hoje</button>:<span>Próxima palavra em <b>{hh}:{mm}:{ss}</b></span>}</footer>
 {modal&&<ModalView type={modal} close={()=>setModal(null)} game={game} date={date} today={today} answer={answer.display} countdown={`${hh}:${mm}:${ss}`} onConfirmHint={()=>{setModal(null);applyHint()}}/>}</main>
}

function ModalView({type,close,game,date,today,answer,countdown,onConfirmHint}:{type:Exclude<Modal,null>;close:()=>void;game:Game;date:string;today:string;answer:string;countdown:string;onConfirmHint:()=>void}){
 const all=Object.values(loadGames()),stats=statistics(all,today),archiveGames=all.filter(g=>g.archive&&g.status!=='playing'),[month,setMonth]=useState(date.slice(0,7)),[copied,setCopied]=useState(false);
 const title={help:'COMO JOGAR',stats:'ESTATÍSTICAS',archive:'ARQUIVO',result:game.status==='won'?'VOCÊ CONSEGUIU!':'FIM DE JOGO',hint:'PEDIR UMA DICA?'}[type];
 const share=async()=>{const digit=(n:number)=>['0️⃣','1️⃣','2️⃣','3️⃣','4️⃣','5️⃣'][n],rows=game.attempts.map(a=>`${digit(a.clue.correct)} ${digit(a.clue.present)} ${digit(a.clue.absent)}`).join('\n'),text=`Termo500 #${dayNumber(game.date)} ${game.status==='won'?game.attempts.length:'X'}/8${game.hintUsed?' 💡':''}\n🟩 🟨 ⬛\n${rows}`;try{if(navigator.share)await navigator.share({text});else{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2600)}}catch{}}
 return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="close" aria-label="Fechar" onClick={close}><X/></button><h2 id="modal-title">{title}</h2>
 {type==='help'&&<div className="copy"><p>Descubra a palavra secreta em até <b>8 tentativas</b>.</p><p>Os blocos à direita mostram apenas quantas letras estão na posição certa, em outra posição ou ausentes. Você decide quais são quais.</p><div className="legend"><span className="correct">2</span> posição certa <span className="present">1</span> outra posição <span className="absent">2</span> ausentes</div><p>Toque numa letra enviada para marcar sua dedução: ausente → presente → certa → neutra. Acentos e cedilha não alteram a comparação.</p><p><b>Espaço</b> insere “_”. A <b>Dica</b> preenche uma palavra compatível depois do primeiro palpite, sem enviá-la.</p><div className="credits"><p>Termo500 é inspirado no <a href="https://term.ooo/" target="_blank" rel="noreferrer">Termo</a> e no <a href="https://word500.com/" target="_blank" rel="noreferrer">Word500</a>.</p><p>Meu Twitter: <a href="https://twitter.com/_forg__" target="_blank" rel="noreferrer">@_forg__</a></p></div></div>}
 {type==='stats'&&<><div className="statgrid"><Stat n={stats.played} t="JOGOS"/><Stat n={`${stats.rate}%`} t="VITÓRIAS"/><Stat n={`${stats.current} (${stats.noHint})`} t="SEQUÊNCIA"/><Stat n={`${stats.max} (${stats.maxNoHint})`} t="MÁXIMA"/></div><h3>DISTRIBUIÇÃO DE PALPITES</h3><Distribution dist={stats.dist} losses={stats.played-stats.wins}/><p className="center">Arquivo: {archiveGames.length} jogados · {archiveGames.filter(g=>g.status==='won').length} resolvidos</p><button className="danger" onClick={()=>{if(confirm('Apagar todo o progresso e estatísticas?')){localStorage.removeItem('termo500.games.v2');location.reload()}}}>Apagar dados locais</button></>}
 {type==='archive'&&<Archive month={month} setMonth={setMonth} today={today} games={all}/>} 
 {type==='hint'&&<div className="hint-warning"><p>Gera uma palavra aleatória que respeita as tentativas prévias.</p><p>Pedir uma dica resultará em um <strong>jogo perdido</strong> e a sua sequência vai <strong>retornar para 0</strong>!</p><p>Deseja pedir uma dica?</p><div><button onClick={close}>CANCELAR</button><button className="confirm-hint" onClick={onConfirmHint}>PEDIR DICA</button></div></div>}
 {type==='result'&&<div className="result"><div className="statgrid result-stats"><Stat n={stats.played} t="JOGOS"/><Stat n={`${stats.rate}%`} t="VITÓRIAS"/><Stat n={stats.current} t="SEQUÊNCIA"/><Stat n={stats.max} t="MELHOR"/></div><h3>DISTRIBUIÇÃO DE TENTATIVAS</h3><Distribution dist={stats.dist} losses={stats.played-stats.wins} result/><p className="solved-line">{game.status==='won'?`${answer} · ${game.attempts.length}/8${game.hintUsed?' · com dica':''}`:`A palavra era ${answer}`}</p><div className="result-actions">{!game.archive&&<p>próxima palavra em <b>{countdown}</b></p>}<button className="primary" onClick={share}><Share2/> COMPARTILHE</button></div></div>}
 </section>{copied&&<div className="copy-toast" role="status">Resultado copiado!</div>}</div>
}
function Stat({n,t}:{n:number|string;t:string}){return <div><b>{n}</b><span>{t}</span></div>}
function Distribution({dist,losses,result=false}:{dist:number[];losses:number;result?:boolean}){const values=[...dist,losses],max=Math.max(...values,1);return <div className={`bars ${result?'result-bars':''}`}>{values.map((n,i)=><div className={i===8?'loss-bar':''} key={i}><b>{i===8?'💀':i+1}</b><i style={{width:`${Math.max(8,n/max*100)}%`}}>{n}</i></div>)}</div>}
function Archive({month,setMonth,today,games}:{month:string;setMonth:(v:string)=>void;today:string;games:Game[]}){const [y,m]=month.split('-').map(Number),days=new Date(y,m,0).getDate(),first=new Date(y,m-1,1).getDay();const shift=(n:number)=>setMonth(new Date(y,m-1+n,1).toISOString().slice(0,7));return <><div className="month"><button onClick={()=>shift(-1)}>‹</button><b>{new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(y,m-1))}</b><button onClick={()=>shift(1)} disabled={month>=today.slice(0,7)}>›</button></div><div className="week">DOM SEG TER QUA QUI SEX SÁB</div><div className="calendar">{Array(first).fill(0).map((_,i)=><i key={`e${i}`}/>)}{Array.from({length:days},(_,i)=>{const d=`${month}-${String(i+1).padStart(2,'0')}`,valid=dayNumber(d)>=1&&d<=today,g=games.find(x=>x.archive&&x.date===d)||games.find(x=>!x.archive&&x.date===d);return <button key={d} disabled={!valid} className={g?.status||''} onClick={()=>location.href=`./?modo=arquivo&data=${d}`}><span>{i+1}</span>{g?.status==='won'?'✓':g?.status==='lost'?'×':''}</button>})}</div><p className="center">Cada dia do arquivo permite uma única partida permanente.</p></>}
